# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-06 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='neighborhood',
            new_name='neighborhoods',
        ),
    ]
