# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-03 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_caption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='img_name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='likes',
            new_name='vote_submissions',
        ),
        migrations.AddField(
            model_name='image',
            name='content',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='design',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, max_length=700),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='usability',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
