# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-06 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0002_auto_20191106_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.TextField(max_length=1000000),
        ),
    ]
