# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-11-03 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor_app', '0003_neighborhood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='image',
            name='content',
        ),
        migrations.RemoveField(
            model_name='image',
            name='design',
        ),
        migrations.RemoveField(
            model_name='image',
            name='link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='usability',
        ),
        migrations.RemoveField(
            model_name='image',
            name='vote_submissions',
        ),
    ]
